import '../styles/globals.css'
import { ReactNode } from 'react'

export const metadata = {
  title: 'My App',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="ja">
      <body className="bg-[#fdf8ee]">{children}</body>
    </html>
  )
}
